'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, HelpCircle } from 'lucide-react';

const faqs = [
  { q: 'How do I generate a battery report?', a: 'Open PowerShell or Command Prompt as Administrator and run: powercfg /batteryreport. This creates an HTML file in your user folder.' },
  { q: 'Is my data safe and private?', a: 'Absolutely. BatteryIQ runs 100% in your browser. Your battery report never leaves your device — no data is uploaded to any server.' },
  { q: 'Does this work on macOS or Linux?', a: 'Currently BatteryIQ only supports Windows battery reports generated by the powercfg command. macOS and Linux support is planned for the future.' },
  { q: 'What is "Wear Level"?', a: 'Wear level is the percentage of original battery capacity that has been permanently lost due to chemical aging. Lower is better — a 10% wear level means your battery still has 90% of its original capacity.' },
  { q: 'How accurate is the health score?', a: 'The health score is calculated from multiple factors including design vs full charge capacity, cycle count, battery life trends, and degradation patterns. It provides a reliable overall assessment of your battery condition.' },
  { q: 'Can I compare multiple battery reports?', a: 'Yes! Upload multiple reports to see a side-by-side comparison of health scores, capacity trends, and usage patterns across different time periods or devices.' },
  { q: 'When should I replace my battery?', a: 'Consider replacement when wear level exceeds 30%, battery life drops below 3 hours for normal use, or if the health score falls below 50 (Grade C or worse).' },
  { q: 'What is the cycle count?', a: 'A cycle count represents one full discharge from 100% to 0%. Most laptop batteries are rated for 300-500 cycles. Partial discharges count as partial cycles.' },
];

export default function FAQSection() {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <section className="w-full px-6 py-20">
      <div className="w-full max-w-[900px] mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <div
            className="inline-flex items-center gap-2 rounded-full mb-4"
            style={{
              padding: '6px 16px',
              background: 'rgba(0,212,255,0.08)',
              border: '1px solid rgba(0,212,255,0.2)',
              color: 'var(--acc2)',
              fontSize: 12,
              fontWeight: 600,
              letterSpacing: '1px',
              textTransform: 'uppercase',
            }}
          >
            <HelpCircle style={{ width: 14, height: 14 }} /> FAQ
          </div>
          <h2 className="font-syne font-bold mb-3" style={{ fontSize: 'clamp(24px, 4vw, 36px)', color: 'var(--tx1)' }}>
            Frequently Asked Questions
          </h2>
          <p style={{ fontSize: 15, color: 'var(--tx2)', maxWidth: 500, margin: '0 auto' }}>
            Everything you need to know about battery health analysis
          </p>
        </div>

        {/* FAQ Items */}
        <div className="flex flex-col gap-3">
          {faqs.map((faq, i) => (
            <div
              key={i}
              className="rounded-2xl overflow-hidden transition-all"
              style={{
                background: 'var(--bg2)',
                border: open === i ? '1px solid var(--bdr2)' : '1px solid var(--bdr)',
              }}
            >
              <button
                onClick={() => setOpen(open === i ? null : i)}
                className="w-full flex items-center justify-between text-left cursor-pointer"
                style={{ padding: '18px 24px' }}
              >
                <span className="font-semibold pr-4" style={{ fontSize: 15, color: 'var(--tx1)' }}>{faq.q}</span>
                <motion.div
                  animate={{ rotate: open === i ? 180 : 0 }}
                  transition={{ duration: 0.2 }}
                  style={{ flexShrink: 0 }}
                >
                  <ChevronDown style={{ width: 18, height: 18, color: 'var(--tx3)' }} />
                </motion.div>
              </button>
              <AnimatePresence>
                {open === i && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.25 }}
                    className="overflow-hidden"
                  >
                    <div style={{ padding: '0 24px 18px', borderTop: '1px solid var(--bdr)', paddingTop: 16 }}>
                      <p className="leading-relaxed" style={{ fontSize: 14, color: 'var(--tx2)' }}>{faq.a}</p>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
